== forge-walkmod-plugin
:idprefix: id_ 
The forge addon enables to run http://www.walkmod.com[Walkmod], an open source tool to apply coding conventions.
All Walkmod commands (install, apply and check) can be executed from Forge. Also, tasks like create a Walkmod plugin skeleton and initilize a Java project with a simple Walkmod configuration file are supported. 
        
== Setup
This Addon requires the following installation steps. Run from forge, the following command.

`addon-install-from-git https://github.com/rpau/forge-walkmod-plugin.git`

== Features
+ `walkmod-apply [verbose = true][printError = false][chains = []][offline = false]`

Applies code the code conventions in your hole project.

+ `walkmod-check [verbose = true][printError = false][chains = []][offline = false]`

Reports the source file that do not follow your code conventions.

+ `walkmod-install [verbose = true] [printError = false]`

Downloads the required Walkmod plugins,

+ `walkmod-new-visitor visitor="foo.MyVisitor"`

Creates an skeleton for a new Walkmod Visitor and updates your plugin descriptor.

+ `walkmod-plugin-setup`

Creates the required project structure / configuration to develop a Walkmod plugin.

+ `walkmod-setup [embedded = true]`

Configures your project to use Walkmod. If the embedded flag is true, it updates your pom.xml with the maven-walkmod-plugin.

=== Add configuration to pom.xml 
To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:

[source,xml]
----
<dependency>
   <groupId>org.walkmod</groupId>
   <artifactId>walkmod</artifactId>
   <classifier>forge-walkmod-plugin</classifier>
   <version>1.0</version>
</dependency>
----


